#!/bin/bash

docker network create rebase-app

docker run -d \
	--network rebase-app --network-alias postgres \
	--name rebase-data \
	-v rebase-postgres-data:/var/lib/postgresql/data \
	-e POSTGRES_PASSWORD=secret \
 	-e POSTGRES_DB=teste \
 	postgres

docker run \
  --rm \
  --name rebase-labs \
  --network rebase-app \
  -w /app \
  -v $(pwd):/app \
  -v labs-gems:/usr/local/bundle \
  -p 3000:3000 \
  ruby \
  bash -c "bundle install && ruby import_from_cvs.rb && ruby server.rb"