#!/bin/bash

docker run \
  --rm \
  --name rebase-labs \
  --network rebase-app \
  -w /app \
  -v $(pwd):/app \
  -v labs-gems:/usr/local/bundle \
  -p 3000:3000 \
  ruby \
  bash -c "bundle install && ruby import_from_cvs.rb && ruby server.rb"